### PR TITLE
Create 1337.sh

### PR DESCRIPTION
**Pull request by WarpWing**

### CODE REVIEW

**Comment by matthewzhaocc** [comment]
Please add unit testing, make the ip of ping a cli argument. And add CI to the unit testing

**Comment by matthewzhaocc** [comment]
The code itself lgtm

**Comment by WarpWing** [comment]
> The code itself lgtm

FFS ur actually making me put effort into this huh? Hold on

**Comment by matthewzhaocc** [comment]
what am I holding on to

**Comment by WarpWing** [comment]
> what am I holding on to

Good question

**Comment by matthewzhaocc** [comment]
Im still holding on to good question, when can I release my hands?

**Comment by WarpWing** [comment]
How about now?

**Pull request closed without merging**
